### ISSUE TITLE
Jobs that throw an exception will prevent further job processing

### ISSUE THREAD

**Issue by LeeSaferite** [AOEpeople/Aoe_Queue#3]
Currently if a job throws an exception it is 100% unhandled in the queue processing cron job. It simply bubbles out and aborts the current queue processing run. This hangs further queue processing due to a default short timeout on message reservations.

A better solution is to wrap the job in a try/catch, log the exceptions, and report the error message as part of the cron run result. Additionally it should trigger the job being an error so that it is obvious that something is wrong.

**Comment by sourcesoldier** [comment]
Find related changes here https://github.com/AOEpeople/Aoe_Queue/tree/exception_retry
